version: "3"
services:
  app:
    build:
      dockerfile: ./app_build/Dockerfile
      context: ../
    command: uvicorn main:app --host 0.0.0.0
    ports:
      - "8000:8000"
    container_name: fast_api_app

  locust:                   
    build:
      dockerfile: ./locust_build/Dockerfile
      context: ../
    command: locust --headless --html=./reports/locust-report.html 
    ports: 
      - "8089:8089"
    volumes:
      - (Set your directory)/reports:/app/reports
