version: "3"
services:
  app:
    build:
      dockerfile: ./app_build/Dockerfile
      context: ../
    command: uvicorn main:app --host 127.0.0.1
    ports:
      - "8000:8000"
    container_name: fast_api_app

  locust:                   
    build:
      dockerfile: ./locust_build/Dockerfile
      context: ../
    command: locust
    ports: 
      - "8089:8089"
